### ISSUE TITLE
P3 bit Configuration not correct in _digit()?

### ISSUE THREAD

**Issue by alexkollert** [beamerkun/stc15clock#15]
hello, I like your project and also have a DIY Clock with the STC15W404AS. Flashed your program on mine and the digits are not shown correctly. After changing two lines in _digit() method to 
P3 |= 0x3C;                                                                                                                                   
P3 &= ~(4 << (3 - pos));
the digits are now shown correctly. Do you have the same issue?

**Comment by jsokol805** [comment]
Hello,
I will check your change on my device today and see if this would work for me too. If that's the case, I'd be happy to merge your changes ;-)
But if my gut feeling is right and this would boil down to differences in hardware (you can schematics for mine under `docs` directory),  we still could work-out some configuration option for this

**Comment by jsokol805** [comment]
Double checked - current state of _digit is correct for my clock. But I've got and idea that we could probably try to detect display type on startup and adjust behavior accordingly.
@alexkollert could you try building `display-detect` branch and check if it now works correctly?

**Comment by alexkollert** [comment]
I tried it and unfortunately does not work. It is not detecting the display correctly. right now i can't tell what is missing.
I attached a schematics  of my board.

![img_1604](https://cloud.githubusercontent.com/assets/7272239/22743333/2eef3ad4-ee1a-11e6-9d8b-f96ec92ad0ba.JPG)

**Comment by jsokol805** [comment]
Thanks for the schematics - seems like you've got proper LED driving circuit, not like mine clock.

Got a few new ideas today to better test/improve the solution - expect a new branch to test today late at night.

**Comment by jsokol805** [comment]
I'm afraid that without circuit modifications we can't detect (only thing I can think of is to measure state of any P2 pin with built-in ADC).
Best I can do is to make it compile-time configurable - please check if setting `COMMON_PIN_ACTIVE_STATE` in stc15_display.h to 0 makes your clock work correctly (this time from `issue-15` branch)

**Comment by alexkollert** [comment]
ok it works with the compile-time configurable. I would suggest to replace the if-else statement with if-else macro. This gets rid of the warnings and correct behaviour will be choosen at compile time. I could do a pull request if you prefer.

**Comment by jsokol805** [comment]
Sure, #if's would certainly look better - if you'd prepare PR I'd be happy to merge it

**Comment by jsokol805** [comment]
Thanks for PR - now i just need to add docs to README about this configuration option and then merge to master.

Is your clock still sold on aliexpress? If so, please post a link to exact seller, I'd like to buy one and play around with it in free time.

**Comment by alexkollert** [comment]
sure, I bought mine on amazon from the seller KKmoon. On aliexpress i found
this
https://www.aliexpress.com/item/2016-new-come-Compact-4-digit-DIY-Digital-LED-Clock-Kit-Light-Control-Temperature-Date-Time/32619347593.html.
Looks 100% the same just the mcu model is different

2017-02-09 15:12 GMT+01:00 Jakub Sokół <notifications@github.com>:
